# Generated by Django 5.1.15 on 2026-07-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_role_cpm_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2nd Year', '2nd Year'), ('3rd Year', '3rd Year')], db_index=True, max_length=10, null=True),
        ),
    ]
