# Generated by Django 5.1.15 on 2026-07-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_changed_password',
            field=models.BooleanField(default=False),
        ),
    ]
