# Generated by Django 5.1.15 on 2026-07-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='candidate',
            new_name='candidates__positio_33c7cf_idx',
            old_name='candidates_ca_positio_0a8f4d_idx',
        ),
    ]
