# Generated by Django 5.1.15 on 2026-07-09 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_rename_candidates_ca_positio_0a8f4d_idx_candidates__positio_33c7cf_idx'),
        ('positions', '0002_position_academic_year'),
        ('voting', '0003_rename_voting_elec_status_stopped_idx_voting_elec_status_7cf43a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mc_number', models.CharField(max_length=100)),
                ('cpm_number', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('declaration_file', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING_REVIEW', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='voting.election')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='positions.position')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('status', 'WITHDRAWN'), _negated=True)), fields=('election', 'member', 'position'), name='unique_active_application_per_member')],
            },
        ),
    ]
