# Generated by Django 5.1.15 on 2026-07-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidateapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateapplication',
            name='photo_url',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
