# Generated by Django 5.1.15 on 2026-07-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidateapplication_photo_url'),
        ('voting', '0004_alter_vote_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplication',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='voting.election'),
        ),
    ]
