# Generated by Django 5.1.15 on 2026-07-09 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_alter_candidateapplication_election'),
        ('voting', '0005_remove_election_unique_active_election_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.election'),
        ),
    ]
