# Generated by Django 5.1.15 on 2026-07-10 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_application_one_per_member'),
        ('positions', '0007_alter_position_academic_year'),
        ('voting', '0006_election_voting_started'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidateapplication',
            name='unique_active_application_per_member_election',
        ),
        migrations.AddConstraint(
            model_name='candidateapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['REJECTED', 'WITHDRAWN']), _negated=True), fields=('election', 'member'), name='unique_active_application_per_member_election'),
        ),
    ]
