# Generated by Django 5.1.15 on 2026-07-11 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_remove_candidateapplication_unique_active_application_per_member_election_and_more'),
        ('positions', '0008_position_max_winners_alter_position_academic_year'),
        ('voting', '0008_vote_unique_per_election'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['election', 'position'], name='cand_election_position_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateapplication',
            index=models.Index(fields=['election', 'status'], name='candapp_elect_status_idx'),
        ),
    ]
