# Generated by Django 5.1.15 on 2026-07-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_election_status_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='election',
            new_name='voting_elec_status_7cf43a_idx',
            old_name='voting_elec_status_stopped_idx',
        ),
        migrations.RenameIndex(
            model_name='election',
            new_name='voting_elec_status_12e66d_idx',
            old_name='voting_elec_status_closed_idx',
        ),
        migrations.RenameIndex(
            model_name='vote',
            new_name='voting_vote_electio_97b316_idx',
            old_name='voting_vote_electio_6ab0f1_idx',
        ),
        migrations.RenameIndex(
            model_name='vote',
            new_name='voting_vote_electio_05e886_idx',
            old_name='voting_vote_electio_2c8e4a_idx',
        ),
        migrations.RenameIndex(
            model_name='vote',
            new_name='voting_vote_member__0d9cbd_idx',
            old_name='voting_vote_member__a3f21b_idx',
        ),
    ]
