# Generated by Django 5.1.15 on 2026-07-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_rename_voting_elec_status_stopped_idx_voting_elec_status_7cf43a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.election'),
        ),
    ]
