# Generated by Django 5.1.15 on 2026-07-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_vote_election'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='election',
            name='unique_active_election',
        ),
        migrations.RemoveIndex(
            model_name='election',
            name='voting_elec_status_7cf43a_idx',
        ),
        migrations.RemoveIndex(
            model_name='election',
            name='voting_elec_status_12e66d_idx',
        ),
        migrations.RemoveField(
            model_name='election',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='election',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='election',
            name='stopped_at',
        ),
        migrations.AddField(
            model_name='election',
            name='application_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='application_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='results_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='election',
            name='voting_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='voting_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=15),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['status'], name='voting_elec_status_1bccd8_idx'),
        ),
    ]
