# Generated by Django 5.1.15 on 2026-07-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_election_voting_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='require_all_positions_filled',
            field=models.BooleanField(default=True),
        ),
    ]
