# Generated by Django 5.1.15 on 2026-07-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2nd Year', '2nd Year'), ('3rd Year', '3rd Year')], max_length=10, null=True),
        ),
    ]
