# Generated by Django 5.1.15 on 2026-07-09 12:35

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_position_academic_year'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='position',
            name='unique_position_name_ci',
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('academic_year'), name='unique_position_name_year_ci'),
        ),
    ]
