# Generated by Django 5.1.15 on 2026-07-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_remove_position_unique_position_name_ci_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='position',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
