# Generated by Django 5.1.15 on 2026-07-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0004_alter_position_options_position_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-importance', 'name']},
        ),
        migrations.RenameField(
            model_name='position',
            old_name='order',
            new_name='importance',
        ),
    ]
