# Generated by Django 5.1.15 on 2026-07-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0005_alter_position_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['importance', 'name']},
        ),
    ]
