# Generated by Django 5.1.15 on 2026-07-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0006_alter_position_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='academic_year',
            field=models.CharField(choices=[('2nd Year', '2nd Year'), ('3rd Year', '3rd Year')], default='3rd Year', max_length=10),
            preserve_default=False,
        ),
    ]
