# Generated by Django 5.1.15 on 2026-07-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0007_alter_position_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='max_winners',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='position',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2nd Year', '2nd Year'), ('3rd Year', '3rd Year')], max_length=10, null=True),
        ),
    ]
