# Generated by Django 5.1.15 on 2026-07-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_memberimportjob'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='memberimportjob',
            new_name='members_mem_status_4f862a_idx',
            old_name='members_mem_status_8a0f0d_idx',
        ),
    ]
