# Generated by Django 5.1.15 on 2026-07-11 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password changed'), ('VOTE_SUBMITTED', 'Vote submitted'), ('ELECTION_CREATED', 'Election created'), ('ELECTION_UPDATED', 'Election updated'), ('ELECTION_DELETED', 'Election deleted'), ('ELECTION_SCHEDULED', 'Election scheduled'), ('ELECTION_VOTING_STARTED', 'Voting started'), ('ELECTION_RESULTS_PUBLISHED', 'Results published'), ('ELECTION_ARCHIVED', 'Election archived'), ('MEMBER_IMPORTED', 'Members imported'), ('MEMBER_UPDATED', 'Member updated'), ('MEMBER_DELETED', 'Member deleted'), ('MEMBERS_BULK_DELETED', 'Members bulk deleted'), ('MEMBERS_CLEARED', 'Members cleared'), ('POSITION_CREATED', 'Position created'), ('POSITION_UPDATED', 'Position updated'), ('POSITION_DELETED', 'Position deleted'), ('CANDIDATE_CREATED', 'Candidate created'), ('CANDIDATE_UPDATED', 'Candidate updated'), ('CANDIDATE_DELETED', 'Candidate deleted'), ('CANDIDATE_PHOTO_UPLOADED', 'Candidate photo uploaded'), ('APPLICATION_SUBMITTED', 'Application submitted'), ('APPLICATION_APPROVED', 'Application approved'), ('APPLICATION_REJECTED', 'Application rejected')], db_index=True, max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx'), models.Index(fields=['actor', '-timestamp'], name='audit_audit_actor_i_dcd783_idx')],
            },
        ),
    ]
