# Generated by Django 5.1.15 on 2026-07-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password changed'), ('VOTE_SUBMITTED', 'Vote submitted'), ('ELECTION_CREATED', 'Election created'), ('ELECTION_UPDATED', 'Election updated'), ('ELECTION_DELETED', 'Election deleted'), ('ELECTION_SCHEDULED', 'Election scheduled'), ('ELECTION_VOTING_STARTED', 'Voting started'), ('ELECTION_RESULTS_PUBLISHED', 'Results published'), ('ELECTION_ARCHIVED', 'Election archived'), ('MEMBER_IMPORTED', 'Members imported'), ('MEMBER_UPDATED', 'Member updated'), ('MEMBER_PASSWORD_RESET', 'Member password reset'), ('MEMBER_DELETED', 'Member deleted'), ('MEMBERS_BULK_DELETED', 'Members bulk deleted'), ('MEMBERS_CLEARED', 'Members cleared'), ('POSITION_CREATED', 'Position created'), ('POSITION_UPDATED', 'Position updated'), ('POSITION_DELETED', 'Position deleted'), ('CANDIDATE_CREATED', 'Candidate created'), ('CANDIDATE_UPDATED', 'Candidate updated'), ('CANDIDATE_DELETED', 'Candidate deleted'), ('CANDIDATE_PHOTO_UPLOADED', 'Candidate photo uploaded'), ('APPLICATION_SUBMITTED', 'Application submitted'), ('APPLICATION_APPROVED', 'Application approved'), ('APPLICATION_REJECTED', 'Application rejected')], db_index=True, max_length=40),
        ),
    ]
